/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ViewNoteIdImport } from './routes/view.$noteId'
import { Route as EditNoteIdImport } from './routes/edit.$noteId'

// Create Virtual Routes

const CreateLazyImport = createFileRoute('/create')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CreateLazyRoute = CreateLazyImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ViewNoteIdRoute = ViewNoteIdImport.update({
  path: '/view/$noteId',
  getParentRoute: () => rootRoute,
} as any)

const EditNoteIdRoute = EditNoteIdImport.update({
  path: '/edit/$noteId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/edit/$noteId': {
      id: '/edit/$noteId'
      path: '/edit/$noteId'
      fullPath: '/edit/$noteId'
      preLoaderRoute: typeof EditNoteIdImport
      parentRoute: typeof rootRoute
    }
    '/view/$noteId': {
      id: '/view/$noteId'
      path: '/view/$noteId'
      fullPath: '/view/$noteId'
      preLoaderRoute: typeof ViewNoteIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CreateLazyRoute,
  EditNoteIdRoute,
  ViewNoteIdRoute,
})

/* prettier-ignore-end */
